export const TOGGLE_FLASH = 'TOGGLE_FLASH';
export const SET_IS_SCANNING = 'SET_IS_SCANNING';
export const SET_SHOW_HELP_MODAL = 'SET_SHOW_HELP_MODAL';
export const SET_HAS_CAMERA_PERMISSION = 'SET_HAS_CAMERA_PERMISSION';
export const SET_SHOW_ENTER_VIN_MODAL = 'SET_SHOW_ENTER_VIN_MODAL';
